### ISSUE TITLE
Segmentation fault on Ubuntu 16.04

### ISSUE THREAD

**Issue by raccettura** [erikkaashoek/Comskip#73]
Example output:
```
$ ./comskip -v 10 /mnt/video/Recorded\ TV/file.ts
Comskip 0.81.098, made using ffmpeg
Donator build
The commandline used was:
./comskip -v 10 "/mnt/video/Recorded TV/file.ts"

Using comskip.ini for initiation values.
Setting verbose level to 10 as per command line.
Segmentation fault (core dumped)
```
Found this in kern.log:
```
Jul  8 17:13:38 tvheadend kernel: [230799.911259] comskip[30702]: segfault at 0 ip 00007fc074a016f8 sp 00007ffd3ee63030 error 4 in libc-2.23.so[7fc074993000+1c0000]
```

**Comment by raccettura** [comment]
Quick check using GDB:

```
Program received signal SIGSEGV, Segmentation fault.
__GI__IO_fwrite (buf=buf@entry=0x43fdf0, size=size@entry=1, count=count@entry=65, fp=fp@entry=0x0) at iofwrite.c:37
37	iofwrite.c: No such file or directory.
```

Think that's about as far as I know how to take it. Curious if anyone else encountered this and/or knows a workaround.

**Comment by raccettura** [comment]
Lastly... works using sudo, suggesting something permission related... gdb confirms that with iofwrite.c error.

**Comment by tmm1** [comment]
Can you post a full backtrace? (Run bt in gen)

**Comment by raccettura** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
__GI__IO_fwrite (buf=buf@entry=0x43fdf0, size=size@entry=1, 
    count=count@entry=65, fp=fp@entry=0x0) at iofwrite.c:37
37	iofwrite.c: No such file or directory.
(gdb) bt
#0  __GI__IO_fwrite (buf=buf@entry=0x43fdf0, size=size@entry=1, 
    count=count@entry=65, fp=fp@entry=0x0) at iofwrite.c:37
#1  0x000000000042c407 in fprintf (
    __fmt=0x43fdf0 '#' <repeats 64 times>, "\n", __stream=0x0)
    at /usr/include/x86_64-linux-gnu/bits/stdio2.h:97
#2  LoadSettings (argc=argc@entry=2, argv=argv@entry=0x7fffffffe588)
    at comskip.c:9156
#3  0x0000000000402ddd in main (argc=2, argv=0x7fffffffe588) at mpeg2dec.c:2173
```

**Comment by erikkaashoek** [comment]
printf failing, using file=NULL, probably because fopen jst before failed. could be for permission indeed.
I made the code a bit more robust
